device: "${device}"
batch_size: ${batch_size}
loss: sparse_categorical_crossentropy
metrics:
  - accuracy
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 1e-3
epochs: ${epochs}
patience: ${patience}


builder: 
  _target_: ml_3.factories.model.KerasBuilder
data_factory:
  _target_: ml_3.factories.ds_fac.KerasDataFactory
flatten: tensorflow.keras.layers.Flatten
dense: tensorflow.keras.layers.Dense