# @package: _global_

device: "${oc.select: device, ???}"
model: "${oc.select: model, ???}"
batch_size: "${oc.select: batch_size, ???}"
loss: sparse_categorical_crossentropy
metrics:
  - accuracy
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 1e-3
epochs: "${oc.select: epochs, ???}"
patience: "${oc.select: patience, ???}"