device: "${device}"
batch_size: ${batch_size}
loss: sparse_categorical_crossentropy
metrics:
  - accuracy
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 1e-3
epochs: ${epochs}
patience: ${patience}


# flatten_cls: tensorflow.keras.layers.Flatten