device: ${oc.select:device, ???}

layers:
  conv1:
    _target_: ml_3.model.layers.Conv2D
    filters: 6
    kernel_size: 5
    strides: 1
    padding: valid
    activation: tanh
    input_shape: ${dataset.input_shape}

  conv2:
    _target_: ml_3.model.layers.Conv2D
    filters: 6
    kernel_size: 2
    strides: 2
    padding: valid
    activation: tanh
    input_shape: ${calc_channels:${..conv1}}

  conv3:
    _target_: ml_3.model.layers.Conv2D
    filters: 16
    kernel_size: 5
    strides: 1
    padding: valid
    activation: tanh
    input_shape: ${calc_channels:${..conv2}}

  conv4:
    _target_: ml_3.model.layers.Conv2D
    filters: 16
    kernel_size: 2
    strides: 2
    padding: valid
    activation: tanh
    input_shape: ${calc_channels:${..conv3}}

  flatten:
      input_shape: ${calc_channels:${..conv4}}

  fc1:
    _target_: ml_3.model.layers.Dense
    in_units: ${flatten:${..flatten.input_shape}}
    out_units: 120
    activation: tanh

  fc2:
    _target_: ml_3.model.layers.Dense
    in_units: ${..fc1.out_units}
    out_units: 84
    activation: tanh

  output_layer:
    _target_: ml_3.model.layers.Dense
    in_units: ${..fc2.out_units}
    out_units: ${dataset.no_target}
    activation: softmax
