device: ${oc.select:device, ???}

layers:
  flatten:
    cls: ${backend.flatten}
    args:
    

  output_layer:
    cls: ${backend.dense}
    args:
      _target_: ml_3.model.layers.Dense
      in_units: ${get_out_units:${dataset.input_shape}}
      out_units: ${dataset.no_target}
      activation: softmax