device: "${oc.select: device, ???}"

layers:
    flatten:
      input_shape: ${oc.select:input_shape}

    hidden1:
      _target_: ml_3.model.layers.Dense
      in_units: ${flatten:${oc.select:input_shape}}
      out_units: 64
      activation: relu

    hidden2:
      _target_: ml_3.model.layers.Dense
      in_units: ${..hidden1.out_units}
      out_units: 32
      activation: tanh

    output_layer:
      _target_: ml_3.model.layers.Dense
      in_units: ${..hidden2.out_units}
      out_units: ${oc.select:no_target, ???}
      activation: softmax