device: ${oc.select:device, ???}

layers:
  flatten:
    cls: ${backend.flatten}
    args:

  hidden1:
    cls: ${backend.dense}
    args:
      _target_: ml_3.model.layers.Dense
      in_units: ${get_out_units:${dataset.input_shape}}
      out_units: 64
      activation: relu

  hidden2:
    cls: ${backend.dense}
    args:
      _target_: ml_3.model.layers.Dense
      in_units: ${..hidden1.args.out_units}
      out_units: 32
      activation: tanh

  output_layer:
    cls: ${backend.dense}
    args:
      _target_: ml_3.model.layers.Dense
      in_units: ${..hidden2.args.out_units}
      out_units: ${dataset.no_target}
      activation: softmax